### ISSUE TITLE
Easier installation method

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#1]
First of all, thanks a lot for this, I wanted something like this!

To test Bridgecraft I had to:
- download the source code
- install carthage
- run carthage
- open and run the project
- find the bynary output
- run Bridgecraft

It would be nice to support an easier installation method such as:
- CocoaPods
- Swift Package Manager
- Mint
- Homebrew

Event if you only support cocoapods would be great for me, since I want to use this inside my project, to automatically generate this bridge.

Thanks

**Comment by lvsti** [comment]
just pushed version 0.0.1 in a binary form to cocoapods, it should appear on the site soon

**Comment by 4brunu** [comment]
I think maybe you show remove this line, because I may want to use this in a iOS project
https://github.com/lvsti/Bridgecraft/blob/86cbad14994049077519a6f5b2a722df26ba8db6/Bridgecraft.podspec#L18

**Comment by lvsti** [comment]
oh, true

**Comment by 4brunu** [comment]
I saw that you updated the podspec, but maybe you also need to release a new version. I'm not sure.

**Comment by lvsti** [comment]
yes, it's just sometimes I need to sleep as well 😄

**Comment by lvsti** [comment]
0.0.3 is out

**Comment by 4brunu** [comment]
Sorry if I have been pushing too hard 😅  but I'm really excited about this because I have a mix code base of objc and swift and I want to use [Sourcery](https://github.com/krzysztofzablocki/Sourcery), and this may be the key to that 😁  If you need some help please let me know 👍
