### ISSUE TITLE
Add comment in top of output saying this code is generated

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#10]
Maybe the output should start with a comment explaining that this code is generated and should not be edited?

Here is the example from [R.swift](https://github.com/mac-cain13/R.swift).
```
//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//
```

This can be useful if a large team is using Bridgecraft, and this way everyone knows that they should not edit this file.

What do you think?

**Comment by lvsti** [comment]
sure, I can add that

**Comment by lvsti** [comment]
03f0379008fa49ddd2a7bce90b52634712902faa
