### ISSUE TITLE
File structure of Bridgecraft 0.3.0 changed in CocoaPods

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#18]
Hi, white testing the new version of Bridgecraft, my scripts start failing, and it was because the file structure changed.

Basically everything that was inside inside `Bridgecraft` moved to `Bridgecraft/Bridgecraft-[current version]`, I attached a screenshot bellow.

<img width="299" alt="screenshot 2018-09-28 at 10 30 36" src="https://user-images.githubusercontent.com/784666/46200598-ed68f200-c309-11e8-9a32-fea07c6af60c.png">

While I can easily change my scripts, I like it better the previous structure, because the new one has the version in the directory name, so every time Bridgecraft updates, I need to change my scripts.

So I propose that the file structure gets reverted to the previous structure.

What do you think?

**Comment by lvsti** [comment]
yup, sorry about that, it's by accident, I'll fix it in the weekend

**Comment by 4brunu** [comment]
No problem! I appreciate the help 👍

**Comment by lvsti** [comment]
I've replaced the release zip on github, please check if that solves it

**Comment by 4brunu** [comment]
It's working! I just needed to clean the cocoapods cache with the following command.
`pod cache clean Bridgecraft`
