### ISSUE TITLE
Add verbose option and more informative errors

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#20]
Sometimes Bridgecraft stop's with some short and generic errors.
When this happen, I need to open the Bridgecraft project, run it with some extra prints, and then run the commands manually in the terminal to get more informative errors.

Here is an example of an error I'm getting now.
When I run Bridgecraft from the command line, this is the output.
```
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
cannot dry-run build for XcodeProject.xcodeproj
make: *** [generate-source] Error 2
```
I have no idea where is the problem.

But when I run the same command that Bridgecraft run's on the terminal `/usr/bin/xcodebuild clean build -dry-run -project XcodeProject.xcodeproj -target XcodeProjectTarget -UseModernBuildSystem=0 -sdk iphonesimulator -destination platform="iOS Simulator,name=iPhone X,OS=latest"`, this is the output.
```
User defaults from command line:
    UseModernBuildSystem = 0

Build settings from command line:
    SDKROOT = iphonesimulator12.0

Prepare build
note: Using legacy build system

=== CLEAN TARGET XcodeProjectTarget OF PROJECT XcodeProjectTarget WITH THE DEFAULT CONFIGURATION (Debug) ===

Check dependencies
[BEROR]No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=i386, VALID_ARCHS=arm64 armv7s).

Create product structure
/bin/mkdir -p /Users/User/Developer/XcodeProject/build/Debug-iphonesimulator/XcodeProjectTarget.app

Clean.Remove clean build/XcodeProjectTarget.build/Debug-iphonesimulator/XcodeProjectTarget.build
    builtin-rm -rf /Users/User/Developer/XcodeProject/build/XcodeProjectTarget.build/Debug-iphonesimulator/XcodeProjectTarget.build

Clean.Remove clean build/Debug-iphonesimulator/XcodeProjectTarget.app
    builtin-rm -rf /Users/User/Developer/XcodeProject/build/Debug-iphonesimulator/XcodeProjectTarget.app

** CLEAN SUCCEEDED **

Prepare build
note: Using legacy build system

=== BUILD TARGET XcodeProjectTarget OF PROJECT XcodeProjectTarget WITH THE DEFAULT CONFIGURATION (Debug) ===

Check dependencies
No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=i386, VALID_ARCHS=arm64 armv7s).

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

Now I know exactly what's the problem.

So I have two suggestions:
    - add a --verbose flag that output's all the shell commands and it's outputs
    - show more informative errors.

If you want I can try to help.

What do you think of this suggestion?

**Comment by lvsti** [comment]
totally agree
