### ISSUE TITLE
Support Interfaces in libraries ?

### ISSUE THREAD

**Issue by toshi0383** [lvsti/Bridgecraft#24]
Is it possible to generate Swift interface of Objective-C sources **in libraries** which is referenced from main app target?

e.g.
```
App/Sources/
- ViewController.swift
- BridgingHeader.h
- Sourcery.out.swift   # <- Here I want to impl CustomStringConvertible describing all properties of MyObject.
...

Pods/MyObjectLib/
- MyObject.h
- MyObject.m
- MyObjectLib-umbrella.h
- MyObjectLib.modulemap
...
```

**Comment by 4brunu** [comment]
Yes, you just need to add `#import "MyObject.h"` to your bridging header.

**Comment by toshi0383** [comment]
@4brunu 
Thanks, but it doesn't work. The file is in library module.

Instead, `@import MyObjectLib;` works partially.
`bridgecraft` successfully outputs `import MyObjectLib` in generated swift file, but not `MyObject` interfaces.

I've been working on this issue in this repo. Please take a look🙏
https://github.com/toshi0383/ObjCSample

You can clone and run `make bootstrap` and see `build/ObjCInterfaces.ignored.swift` to confirm.

**Comment by toshi0383** [comment]
Maybe one way is to run `xcodegen` to create `MyObjectLib.xcodeproj` as an app target with bridging header, then run `bridgecraft` against it.

**Comment by 4brunu** [comment]
If you remove `use_frameworks!` from the Podfile and add `#import <GoogleInteractiveMediaAds/GoogleInteractiveMediaAds.h>` to the bridging header, the Bridgecraft output already contains everything in GoogleInteractiveMediaAds.
After running Sourcery manually, this is what I get.
```
extension A {
    open override var description: String {
        return "Hello I'm A instance."
    }
}
extension DeallocTracker {
    open override var description: String {
        return "Hello I'm DeallocTracker instance."
    }
}
extension Hello {
    internal override var description: String {
        return "Hello I'm Hello instance."
    }
}
extension IMAAVPlayerContentPlayhead {
    open override var description: String {
        return "Hello I'm IMAAVPlayerContentPlayhead instance."
    }
}
extension IMAAVPlayerVideoDisplay {
    open override var description: String {
        return "Hello I'm IMAAVPlayerVideoDisplay instance."
    }
}
extension IMAAd {
    open override var description: String {
        return "Hello I'm IMAAd instance."
    }
}
extension IMAAdDisplayContainer {
    open override var description: String {
        return "Hello I'm IMAAdDisplayContainer instance."
    }
}
extension IMAAdError {
    open override var description: String {
        return "Hello I'm IMAAdError instance."
    }
}
extension IMAAdEvent {
    open override var description: String {
        return "Hello I'm IMAAdEvent instance."
    }
}
extension IMAAdLoadingErrorData {
    open override var description: String {
        return "Hello I'm IMAAdLoadingErrorData instance."
    }
}
extension IMAAdPodInfo {
    open override var description: String {
        return "Hello I'm IMAAdPodInfo instance."
    }
}
extension IMAAdsLoadedData {
    open override var description: String {
        return "Hello I'm IMAAdsLoadedData instance."
    }
}
extension IMAAdsLoader {
    open override var description: String {
        return "Hello I'm IMAAdsLoader instance."
    }
}
extension IMAAdsManager {
    open override var description: String {
        return "Hello I'm IMAAdsManager instance."
    }
}
extension IMAAdsRenderingSettings {
    open override var description: String {
        return "Hello I'm IMAAdsRenderingSettings instance."
    }
}
extension IMAAdsRequest {
    open override var description: String {
        return "Hello I'm IMAAdsRequest instance."
    }
}
extension IMACompanionAdSlot {
    open override var description: String {
        return "Hello I'm IMACompanionAdSlot instance."
    }
}
extension IMACuepoint {
    open override var description: String {
        return "Hello I'm IMACuepoint instance."
    }
}
extension IMALiveStreamRequest {
    open override var description: String {
        return "Hello I'm IMALiveStreamRequest instance."
    }
}
extension IMAPictureInPictureProxy {
    open override var description: String {
        return "Hello I'm IMAPictureInPictureProxy instance."
    }
}
extension IMASettings {
    open override var description: String {
        return "Hello I'm IMASettings instance."
    }
}
extension IMAStreamManager {
    open override var description: String {
        return "Hello I'm IMAStreamManager instance."
    }
}
extension IMAStreamRequest {
    open override var description: String {
        return "Hello I'm IMAStreamRequest instance."
    }
}
extension IMAVODStreamRequest {
    open override var description: String {
        return "Hello I'm IMAVODStreamRequest instance."
    }
}
```

**Comment by toshi0383** [comment]
Awesome!
What if I need to use `use_frameworks!` though?
Maybe writing script to automate that "pod install for bridgecraft" process?

**Comment by 4brunu** [comment]
Hum, in that case I'm not sure... If you find a solution please post it here 🙂 
Maybe @lvsti knows has some idea?

**Comment by lvsti** [comment]
> What if I need to use `use_frameworks!` though?

It's tricky because bridgecraft cooks from what comes out of the preprocessing stage and module imports are opaque. So as @4brunu said, `@import`s should be first replaced with `#import`s. But that's not sufficient as bridgecraft calls clang with `-fmodules` and `-fimplicit-modules` enabled, which automatically converts framework header imports into module imports. If you remove these flags then the framework header contents will actually appear in the generated swift file. There is one tiny problem though: not just your framework but all the system frameworks will be expanded, resulting in a 7+ MB output (good luck parsing that with Sourcery...).

So the solution (if there is any) would be to discriminate system and user frameworks, but I'm not a clang expert and the only way I saw for that is to specify `-fno-implicit-modules` and reference each and every system framework/module with `-fmodule-file=...`, which sounds like a nightmare to me. But let us know if you figure it out!

**Comment by toshi0383** [comment]
@lvsti Thanks!!

> 7+ MB output (good luck parsing that with Sourcery...).

I tried with Sourcery to see how it goes, but it hanged after consuming more than 30GB of memory. (according to Activity Monitor)
Adding `-fno-implicit-modules` to `compilerFlagsUnwrapped` made no change for me. It still emitted 7.2 MB output.

I'll try https://github.com/lvsti/Bridgecraft/issues/24#issuecomment-437350882 approach. I guess it's not ideal, but looks a lot easier.

**Comment by 4brunu** [comment]
@toshi0383 do you see any disadvantage in removing `use_frameworks!` or any use case where you need it?

**Comment by toshi0383** [comment]
I thought there would be some disadvantages but I didn't find any. Module name space is not available anymore, but looks like it's not a big deal for us. (for now)
We're just considering to migrate from Swift dynamic frameworks to static frameworks, so maybe it's a good timing to switch Objective-C library to static library as well. 👌

**Comment by joesus** [comment]
FWIW to future explorers. Did not need to remove `use_frameworks!` from Podfile. Perhaps something changed with one of the dependencies.

**Tools**:
Xcode: Version 10.3 (10G8) 
Cocoapods: 1.7.5
Using Bridgecraft (0.5.0)
