### ISSUE TITLE
Add an option to write the output to a file

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#6]
It would be great to write the output to a single file, like [Sourcery](https://github.com/krzysztofzablocki/Sourcery) or [R.swift](https://github.com/mac-cain13/R.swift), I think that way would be easier to integrate with [Sourcery](https://github.com/krzysztofzablocki/Sourcery)

**Comment by lvsti** [comment]
what's wrong with `$ bridgecraft .... > output.swift` ?

**Comment by 4brunu** [comment]
Nothing, actually I didn't remember that option...
Maybe it's a good idea to add that to the readme.
What do you think?

**Comment by 4brunu** [comment]
Just pinging to try to close the last issue 😀 
Do you think that this should be on readme or it's not worth it?

**Comment by lvsti** [comment]
13bf333a49e3b72592c37b69507daea062d6ad89

**Comment by 4brunu** [comment]
Looks great, thanks! 👍
