### ISSUE TITLE
Named parameters

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#7]
Using Bridgecraft with named parameters would make it easier to use it, because that way the order of the parameters wouldn't matter, and it would be easier to know what is each parameter

**Comment by 4brunu** [comment]
This is working great in [0.0.3](https://github.com/lvsti/Bridgecraft/releases/tag/0.0.3), thanks 👍 
Maybe this should be documented in readme or something?

**Comment by lvsti** [comment]
8bb70980aeb11b28e84f8636c06665547f6b4eef

**Comment by 4brunu** [comment]
Thats perfect, thanks! 👍
