### ISSUE TITLE
Add an option to run Bridgecraft against the simulator

### ISSUE THREAD

**Issue by 4brunu** [lvsti/Bridgecraft#8]
Every new project that I created returned an error because it was running without code signing configured.

It would be great to have an option to run Bridgecraft with the simulator.

To archive that, I think there are two new options required `destination` and `sdk`
```
  -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' \
  -sdk iphonesimulator \
```
[Here](http://www.mokacoding.com/blog/how-to-always-run-latest-simulator-cli/) is the source where I got this.

What do you think?

**Comment by lvsti** [comment]
makes perfect sense

**Comment by 4brunu** [comment]
This is working great in [0.0.3](https://github.com/lvsti/Bridgecraft/releases/tag/0.0.3), thanks 👍

**Comment by 4brunu** [comment]
One more thing, maybe this should be documented in readme or something?

**Comment by lvsti** [comment]
8bb70980aeb11b28e84f8636c06665547f6b4eef

**Comment by 4brunu** [comment]
Thats perfect, thanks! 👍
